export const appPaths = {
  HOME: '/',
  SERVICE_RECORD_BY_FACT: '/service/by-fact',
  SERVICE_WORK_SCHEDULE: '/service/work-schedule',
  SERVICE_TASKS: '/service/tasks',
  SERVICE_SALARY: '/service/salary',
  SERVICE_REMOTE_EMPLOYEES: '/service/remote-employees',
  SERVICE_FACE_ID: '/service/face-id',
  SERVICE_MOBILE_APP: '/service/mobile-app',

  DOCTORS: '/doctors',
  ABOUT_CLINIC: '/about-clinic',
  ABOUT_US: '/about-us',
  CALL_CENTER: '/call-center',
  CARDIOLOGY: '/cardiology',
  CONTACTS: '/contacts',
  CONTROL: '/control',
  HEALER: '/healer',
  NEUROSURGERY: '/neurosurgery',
  NEWS: '/news',
  NEWS_DETAIL: '/news-detail',
  ORTHOPEDICS: '/orthopedics',
  OTOLARYNGOLOGY: '/otolaryngology',
  PHYSIOTHERAPY: '/physiotherapy',
  RESIDENCY: '/residency',
<<<<<<< HEAD
  SUBMISSION: '/submission',
};
=======
  ABOUT_CLINIC: '/about-clinic',
  CONTACTS: '/contacts',
  CONTROL: '/control',
  HEALER: '/healer',
  NEWS: '/news',
  NEWS_DETAIL: '/news-detail',
  ORTHOPEDICS: '/orthopedics',
  ALLSERVICES: '/allservices',


  
  ALLERGIST: '/allergist',
  DERMATOLOGIST: '/dermatologist',
  ENDOCRINOLOGIST: '/endocrinologist',
  GASTROENTEROLOGIST: '/gastroenterologist',
  GYNECOLOGIST: '/gynecologist',
  HEPATOLOGIST: '/hepatologist',
  INFECTIOUSDOC: '/infectiousdoc',
  INPATIENTWARD: '/inpatient-ward',
  LABORATORY: '/laboratory',
  MASSAGETHERAPY: '/massage-therapy',
  NEUROLOGIST: '/neurologist',
  OPERATINGROOM: '/operating-room',
  PEDIATRICGASTRO: '/pediatric-gastro',
  PEDIATRICIAN: '/pediatrician',
  PEDIATRICNEURO: '/pediatric-neuro',
  PROCEDUREROOM: '/procedure-room',
  PROCTOLOGIST: '/proctologist',
  PULMONOLOGIST: '/pulmonologist',
  RHEUMATOLOGIST: '/rheumatologist',
  THERAPIST: '/therapist',
  TRAUMASURGEON: '/trauma-surgeon',
  ULTRASOUND: '/ultrasound',
  UROLOGIST: '/urologist',
  XRAY: '/xray',
};
>>>>>>> ec83732 (Bo'lim yangilandi)
